# Generated by Django 4.2 on 2025-05-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='cpas',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='uname',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='pas',
            new_name='username',
        ),
    ]
