# Generated by Django 4.2 on 2025-05-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_password1_usersignup_cpas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='cpas',
        ),
    ]
