# Generated by Django 4.2 on 2025-05-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_pas_usersignup_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
