# Generated by Django 4.2 on 2025-05-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_usersignup_address_alter_usersignup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='address',
            field=models.TextField(),
        ),
    ]
