# Generated by Django 4.2 on 2025-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_usercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submited', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('service', models.CharField(choices=[('Diagnostic Test', 'Diagnostic Test'), ('Engine Servicing', 'Engine Servicing'), ('Tires Replacement', 'Tires Replacement'), ('Oil Changing', 'Oil Changing')], max_length=50)),
                ('date', models.DateField()),
                ('specialrequest', models.TextField()),
            ],
        ),
    ]
