# Generated by Django 4.2 on 2025-05-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_cpas_usersignup_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='password1',
            new_name='cpas',
        ),
        migrations.RenameField(
            model_name='usersignup',
            old_name='password2',
            new_name='pas',
        ),
    ]
