# Generated by Django 4.2 on 2025-05-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_usersignup_cpas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='pas',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='address',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.TextField(),
        ),
    ]
