# Generated by Django 4.2 on 2025-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_bookservice_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookservice',
            name='service',
            field=models.CharField(choices=[('Diagnostic Test', 'Diagnostic Test'), ('Engine Servicing', 'Engine Servicing'), ('Tires Replacement', 'Tires Replacement'), ('Oil Changing', 'Oil Changing'), ('Car Wash', 'Car Wash'), ('Battery Check', 'Battery Check'), ('Brake Inspection', 'Brake Inspection'), ('AC Service', 'AC Service')], max_length=50),
        ),
    ]
